apiVersion : apps/v1
kind: Deployment
metadata:
  name: securedewpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securedewpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: securedewpipelinesjavascriptdocker 
    spec:
      containers:
        - name: securedewpipelinesjavascriptdocker 
          image: cwppoccontainerregistry.azurecr.io/securedewpipelinesjavascriptdocker
          ports:
          - containerPort: 8080